version: '3.1'

services:
  golang:
    build:
      context: .
    ports:
      - 6060:6060
    depends_on:
      - postgres
  postgres:
    build:
      context: ./db
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: sample
      POSTGRES_USER: admin
      POSTGRES_DB: firecontrol

#    volumes:
#      - .:/go/src/app
